# Multi Agent Data Analysis with Crew AI
# Copyright (c) 2025 Sowmiyan S
# Licensed under the MIT License

"""
PDF export — professional executive report.

Improvements:
- Cover page: project title (filename) + timestamp.
- Data Insights section: per-column min/max/mean/median/std for numerics,
  top categories for categoricals — placed after the dataset summary.
- No empty spacers for sections with no content.
- KeepTogether for insight cards to prevent orphaned headers.
- export_pdf_cached() wrapper used by app.py.
"""

import io
import re
from datetime import datetime
from io import BytesIO
from pathlib import Path

import pandas as pd
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# ---------------------------------------------------------------------------
# Two-pass Canvas — Page X of Y + Corporate Rules
# ---------------------------------------------------------------------------

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for dynamic page count and corporate header/footer rules."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)

        if self._pageNumber > 1:
            self.line(54, 735, 558, 735)
            self.drawString(54, 742, "EXECUTIVE BUSINESS INTELLIGENCE REPORT")
            self.drawRightString(558, 742, "CONFIDENTIAL")

        self.line(54, 60, 558, 60)
        self.setFont("Helvetica", 8)
        self.drawString(54, 45, "Generated by Agentic Data Analyst System")
        self.drawRightString(558, 45, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


# ---------------------------------------------------------------------------
# Markdown → ReportLab HTML
# ---------------------------------------------------------------------------

def _md_to_html(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.*?)\*",     r"<i>\1</i>", text)
    text = (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
    )
    text = (
        text.replace("&lt;b&gt;",  "<b>").replace("&lt;/b&gt;", "</b>")
            .replace("&lt;i&gt;",  "<i>").replace("&lt;/i&gt;", "</i>")
    )
    return text.strip()


# ---------------------------------------------------------------------------
# Data Insights table builder
# ---------------------------------------------------------------------------

def _build_insights_table(df: pd.DataFrame, body_style, header_style, secondary_color) -> list:
    """
    Build a Data Insights table showing per-column statistics.
    Returns a list of flowables (may be empty if no numeric cols).
    """
    flowables = []

    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    cat_cols     = df.select_dtypes(include=["object", "category"]).columns.tolist()

    # ── Numeric stats table ──────────────────────────────────────────────────
    if numeric_cols:
        header_row = [
            Paragraph("<b>Column</b>", header_style),
            Paragraph("<b>Min</b>",    header_style),
            Paragraph("<b>Max</b>",    header_style),
            Paragraph("<b>Mean</b>",   header_style),
            Paragraph("<b>Median</b>", header_style),
            Paragraph("<b>Std Dev</b>",header_style),
            Paragraph("<b>Missing%</b>", header_style),
        ]
        rows = [header_row]

        for col in numeric_cols[:20]:   # cap at 20 columns
            s      = df[col]
            miss   = round(s.isnull().sum() / max(len(df), 1) * 100, 1)
            s_num  = s.dropna()
            row = [
                Paragraph(str(col), body_style),
                Paragraph(f"{s_num.min():.4g}" if not s_num.empty else "—", body_style),
                Paragraph(f"{s_num.max():.4g}" if not s_num.empty else "—", body_style),
                Paragraph(f"{s_num.mean():.4g}" if not s_num.empty else "—", body_style),
                Paragraph(f"{s_num.median():.4g}" if not s_num.empty else "—", body_style),
                Paragraph(f"{s_num.std():.4g}" if len(s_num) > 1 else "—", body_style),
                Paragraph(f"{miss}%", body_style),
            ]
            rows.append(row)

        tbl = Table(rows, colWidths=[120, 55, 55, 55, 55, 55, 55])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  colors.HexColor("#f1f5f9")),
            ("LINEBELOW",     (0, 0), (-1, 0),  1.2, secondary_color),
            ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID",     (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ]))
        flowables.append(tbl)
        flowables.append(Spacer(1, 8))

    # ── Categorical top-values table ─────────────────────────────────────────
    if cat_cols:
        cat_header = [
            Paragraph("<b>Column</b>",     header_style),
            Paragraph("<b>Top Values (count)</b>", header_style),
            Paragraph("<b>Unique</b>",     header_style),
            Paragraph("<b>Missing%</b>",   header_style),
        ]
        cat_rows = [cat_header]

        for col in cat_cols[:10]:
            s     = df[col]
            miss  = round(s.isnull().sum() / max(len(df), 1) * 100, 1)
            unique = s.nunique()
            top3  = s.value_counts().head(3)
            top_str = ", ".join(f"{v}({c})" for v, c in top3.items()) if not top3.empty else "—"
            cat_rows.append([
                Paragraph(str(col), body_style),
                Paragraph(top_str[:80], body_style),
                Paragraph(str(unique), body_style),
                Paragraph(f"{miss}%", body_style),
            ])

        cat_tbl = Table(cat_rows, colWidths=[100, 280, 55, 65])
        cat_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  colors.HexColor("#f1f5f9")),
            ("LINEBELOW",     (0, 0), (-1, 0),  1.2, secondary_color),
            ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID",     (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ]))
        flowables.append(cat_tbl)

    return flowables


# ---------------------------------------------------------------------------
# PDF Generation
# ---------------------------------------------------------------------------

def export_pdf(result: dict, filename: str = "") -> bytes:
    """Build and return a professional executive PDF report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=72,
        bottomMargin=72,
    )
    story = []
    styles = getSampleStyleSheet()

    primary_color   = colors.HexColor("#1e1b4b")
    secondary_color = colors.HexColor("#4f46e5")
    text_color      = colors.HexColor("#0f172a")
    muted_color     = colors.HexColor("#475569")

    title_style = ParagraphStyle("DocTitle", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=24, leading=30,
        textColor=primary_color, spaceAfter=4)
    subtitle_style = ParagraphStyle("DocSubTitle", parent=styles["Normal"],
        fontName="Helvetica", fontSize=11, leading=15,
        textColor=secondary_color, spaceAfter=6)
    meta_style = ParagraphStyle("Meta", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9, leading=13,
        textColor=muted_color, spaceAfter=12)
    h1_style = ParagraphStyle("H1", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=15, leading=20,
        textColor=primary_color, spaceBefore=16, spaceAfter=8, keepWithNext=True)
    h2_style = ParagraphStyle("H2", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=11, leading=15,
        textColor=secondary_color, spaceBefore=10, spaceAfter=4, keepWithNext=True)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
        fontName="Helvetica", fontSize=10, leading=15,
        textColor=text_color, spaceAfter=5)
    header_style = ParagraphStyle("TblHdr", parent=styles["Normal"],
        fontName="Helvetica-Bold", fontSize=9, leading=12,
        textColor=primary_color)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
        fontName="Helvetica", fontSize=9.5, leading=14,
        textColor=text_color, leftIndent=14, firstLineIndent=-10, spaceAfter=7)

    # ── Cover page ────────────────────────────────────────────────────────────
    report_title = result.get("report_title") or filename or "Data Analysis Report"
    report_goal  = result.get("goal") or ""
    timestamp    = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    cover_content = [
        Paragraph(f"<b>{report_title.upper()}</b>", title_style),
        Paragraph("Autonomous Business Intelligence &amp; Strategy Recommendations", subtitle_style),
        Paragraph(f"Dataset: <b>{filename or 'dataset.csv'}</b>", meta_style),
        Paragraph(f"Generated: {timestamp} (Live Analysis)", meta_style),
    ]
    if report_goal:
        cover_content.append(Spacer(1, 6))
        cover_content.append(Paragraph(f"<b>Project Goal / Objective:</b> {report_goal}", ParagraphStyle("GoalStyle", parent=body_style, fontName="Helvetica", fontSize=9.5, textColor=muted_color)))

    cover_table = Table([[cover_content]], colWidths=[504])
    cover_table.setStyle(TableStyle([
        ("LINELEFT",      (0, 0), (0, -1), 5, secondary_color),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 14))

    # Parse structured sections from insights text
    raw_insights = result.get("insights", "").strip()
    objectives_text = ""
    stats_text = ""
    strategic_text = ""
    warnings_text = ""

    if raw_insights:
        sections = re.split(r"###\s+", raw_insights)
        for sec in sections:
            lines = sec.split("\n")
            if not lines or not lines[0].strip():
                continue
            header = lines[0].strip().lower()
            content = "\n".join(lines[1:]).strip()

            if "objective" in header or "goal" in header:
                objectives_text = content
            elif "stat" in header:
                stats_text = content
            elif "insight" in header:
                strategic_text = content
            elif "warning" in header or "alert" in header:
                warnings_text = content

        # Fallback if no sections parsed
        if not strategic_text and not objectives_text:
            strategic_text = raw_insights

    # ── Dataset Summary callout ───────────────────────────────────────────────
    df = result.get("dataframe")
    if df is not None and isinstance(df, pd.DataFrame):
        cols_preview = f"{', '.join(str(c) for c in df.columns[:8])}{'...' if len(df.columns) > 8 else ''}"
        numeric_count = len(df.select_dtypes(include=["number"]).columns)
        cat_count     = len(df.select_dtypes(include=["object", "category"]).columns)

        box_data = [
            [Paragraph("<b>Dataset Summary</b>", h2_style), Paragraph("", body_style)],
            [Paragraph("Total Records Analyzed",   body_style), Paragraph(f"<b>{df.shape[0]:,}</b>", body_style)],
            [Paragraph("Total Columns",            body_style), Paragraph(f"<b>{df.shape[1]}</b>", body_style)],
            [Paragraph("Numeric Columns",          body_style), Paragraph(f"<b>{numeric_count}</b>", body_style)],
            [Paragraph("Categorical Columns",      body_style), Paragraph(f"<b>{cat_count}</b>", body_style)],
            [Paragraph("Columns Featured",         body_style), Paragraph(cols_preview, body_style)],
        ]
        summary_box = Table(box_data, colWidths=[160, 320])
        summary_box.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX",           (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ("LINEBELOW",     (0, 0), (-1, 0),  1.5, secondary_color),
            ("TOPPADDING",    (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING",   (0, 0), (-1, -1), 12),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(summary_box)
        story.append(Spacer(1, 12))

        # ── Data Insights (min/max/mean/median + top categories) ─────────────
        story.append(Paragraph("📊 Data Insights Summary", h1_style))
        story.append(Paragraph(
            "Per-column statistical summary of the cleaned dataset.",
            body_style,
        ))
        insight_flowables = _build_insights_table(df, body_style, header_style, secondary_color)
        if insight_flowables:
            story.extend(insight_flowables)
        else:
            story.append(Paragraph("No numeric or categorical columns to summarize.", body_style))
        story.append(Spacer(1, 10))

    # ── Cleaning steps ────────────────────────────────────────────────────────
    cleaning_text = result.get("cleaning_steps", "").strip()
    if cleaning_text:
        story.append(Paragraph("🧹 Data Cleaning Audit Trail", h1_style))
        for raw in cleaning_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if line:
                story.append(Paragraph(f"✔ &nbsp; {_md_to_html(line)}", bullet_style))
        story.append(Spacer(1, 10))

    # ── Objectives Section (if parsed) ────────────────────────────────────────
    if objectives_text:
        story.append(Paragraph("🎯 Project Objectives &amp; Scope", h1_style))
        story.append(Paragraph(objectives_text.replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 10))

    # ── Relations ─────────────────────────────────────────────────────────────
    relations_text = result.get("relations", "").strip()
    if relations_text:
        story.append(Paragraph("🔗 Key Correlation &amp; Relationship Map", h1_style))
        for raw in relations_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if line:
                story.append(Paragraph(f"🔗 &nbsp; {_md_to_html(line)}", bullet_style))
        story.append(Spacer(1, 10))

    # ── Strategic Insights (McKinsey cards) ───────────────────────────────────
    if strategic_text:
        story.append(Paragraph("💡 Strategic Business Insights", h1_style))
        insight_items  = re.split(r"\d+\.\s+", strategic_text)
        insight_count  = 0

        for item in insight_items:
            item = item.strip()
            if not item:
                continue
            insight_count += 1
            formatted = _md_to_html(item)

            parts = formatted.split("<br/>")
            if len(parts) < 2:
                parts = formatted.split("\n")

            card_content = []
            for part in parts:
                part = part.strip()
                if not part:
                    continue
                if "Observation" in part:
                    card_content.append(Paragraph(part, body_style))
                elif "Implication" in part or "Business Implication" in part:
                    card_content.append(Paragraph(
                        f"<font color='#475569'><i>{part}</i></font>", body_style))
                elif "Strategy" in part or "Actionable Strategy" in part:
                    card_content.append(Paragraph(
                        f"<font color='#4f46e5'><b>{part}</b></font>", body_style))
                else:
                    card_content.append(Paragraph(part, body_style))

            if not card_content:
                continue

            lbl_para = Paragraph(
                f"<b>Insight {insight_count}</b>",
                ParagraphStyle("InsLbl", parent=body_style, fontName="Helvetica-Bold",
                               fontSize=11, textColor=primary_color, spaceBefore=4, spaceAfter=2),
            )
            card_table = Table([[card_content]], colWidths=[504])
            card_table.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ("LINELEFT",      (0, 0), (0, -1),  3, colors.HexColor("#6366f1")),
                ("LEFTPADDING",   (0, 0), (-1, -1), 12),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ]))
            story.append(KeepTogether([lbl_para, card_table, Spacer(1, 8)]))

    # ── Warnings & Alerts ─────────────────────────────────────────────────────
    if warnings_text and not "no warnings" in warnings_text.lower() and not "none" in warnings_text.lower():
        story.append(Paragraph("⚠️ Business Risks &amp; Critical Alerts", h1_style))
        warning_content = [
            Paragraph(warnings_text.replace("\n", "<br/>"), ParagraphStyle("WarnStyle", parent=body_style, fontSize=9.5, textColor=colors.HexColor("#991b1b")))
        ]
        warning_table = Table([[warning_content]], colWidths=[504])
        warning_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#fef2f2")),
            ("LINELEFT",      (0, 0), (0, -1),  4, colors.HexColor("#f43f5e")),
            ("LEFTPADDING",   (0, 0), (-1, -1), 12),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#fee2e2")),
        ]))
        story.append(KeepTogether([warning_table, Spacer(1, 10)]))

    # ── Conclusion ────────────────────────────────────────────────────────────
    story.append(Paragraph("🏁 Executive Conclusion &amp; Next Steps", h1_style))
    conclusion_text = (
        "The automated data pipeline has successfully validated, cleaned, and evaluated the dataset "
        "under the specified project guidelines. To maximize return on these insights, management is advised "
        "to prioritize the Actionable Strategy recommendations outlined in the insights section, address the warnings "
        "disclosed, and leverage the visual intelligence charts for stakeholder presentations."
    )
    story.append(Paragraph(conclusion_text, body_style))
    story.append(Spacer(1, 10))

    # ── Visualizations ───────────────────────────────────────────────────────
    output_dir = result.get("output_dir", Path("outputs"))
    png_files  = list(Path(output_dir).glob("*.png"))

    if png_files:
        story.append(PageBreak())
        story.append(Paragraph("📈 Visualized Business Intelligence", h1_style))
        story.append(Paragraph(
            "Visual evidence of the data relationships identified by the agents.",
            body_style,
        ))
        story.append(Spacer(1, 8))

        for png_file in png_files:
            try:
                with PILImage.open(png_file) as img:
                    orig_w, orig_h = img.size
                max_w, max_h = 460, 280
                aspect = orig_h / orig_w
                if aspect > (max_h / max_w):
                    new_h = max_h
                    new_w = new_h / aspect
                else:
                    new_w = max_w
                    new_h = new_w * aspect

                fig_title = Paragraph(
                    f"<b>Figure: {png_file.stem}</b>",
                    ParagraphStyle("FigTitle", parent=body_style, fontName="Helvetica-Bold",
                                   textColor=primary_color, spaceBefore=10, spaceAfter=4, keepWithNext=True),
                )
                img_flow  = Image(str(png_file), width=new_w, height=new_h)
                img_table = Table([[img_flow]], colWidths=[480])
                img_table.setStyle(TableStyle([
                    ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
                    ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ("BACKGROUND",    (0, 0), (-1, -1), colors.white),
                    ("TOPPADDING",    (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]))
                story.append(KeepTogether([fig_title, img_table, Spacer(1, 12)]))
            except Exception as exc:
                story.append(Paragraph(f"Could not load image {png_file.name}: {exc}", body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


# ---------------------------------------------------------------------------
# Cached wrapper (used by app.py)
# ---------------------------------------------------------------------------

_pdf_cache: dict = {}


def export_pdf_cached(
    cache_key: str,
    filename: str = "",
    result_cleaning:  str = "",
    result_relations: str = "",
    result_insights:  str = "",
    result_code:      str = "",
    output_dir_str:   str = "outputs",
    df_csv:           str = "",
) -> bytes:
    """
    Build (or return cached) PDF bytes from serialized result components.
    Uses an in-process dict cache keyed by content hash to avoid rebuilding
    identical PDFs on every Streamlit rerun.
    """
    if cache_key in _pdf_cache:
        return _pdf_cache[cache_key]

    # Reconstruct DataFrame from CSV string
    df = None
    if df_csv:
        try:
            df = pd.read_csv(io.StringIO(df_csv))
        except Exception:
            df = None

    result = {
        "dataframe":      df,
        "cleaning_steps": result_cleaning,
        "relations":      result_relations,
        "insights":       result_insights,
        "code":           result_code,
        "output_dir":     output_dir_str,
    }

    pdf_bytes = export_pdf(result, filename=filename)
    _pdf_cache[cache_key] = pdf_bytes
    return pdf_bytes
