# Multi Agent Data Analysis with Crew AI
# Copyright (c) 2025 Sowmiyan S
# Licensed under the MIT License

"""
PDF export logic, upgraded for executive corporate presentations.
Features:
- NumberedCanvas: Two-pass page numbering ("Page X of Y") with professional header/footer rules.
- McKinsey-style Executive Callout boxes (tables with accent left-borders and backgrounds).
- Automatic Markdown-to-PDF formatting (replaces agent's `**bold**` with ReportLab `<b>bold</b>`).
- Clean typography and professional spacing.
"""

import re
from io import BytesIO
from pathlib import Path

import streamlit as st
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# ---------------------------------------------------------------------------
# Two-pass Canvas for Page X of Y & Corporate Rules
# ---------------------------------------------------------------------------

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print the total page count
    along with corporate running headers and footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))   # slate grey
        self.setStrokeColor(colors.HexColor("#cbd5e1")) # border line
        self.setLineWidth(0.5)

        # Header rule & title (drawn on all pages after page 1)
        if self._pageNumber > 1:
            self.line(54, 735, 558, 735)
            self.drawString(54, 742, "EXECUTIVE BUSINESS INTELLIGENCE REPORT")
            self.drawRightString(558, 742, "CONFIDENTIAL")

        # Footer rule & details (drawn on all pages)
        self.line(54, 60, 558, 60)
        self.setFont("Helvetica", 8)
        self.drawString(54, 45, "Generated by Agentic Data Analyst System")
        self.drawRightString(558, 45, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


# ---------------------------------------------------------------------------
# Markdown to PDF formatting parser
# ---------------------------------------------------------------------------

def _format_markdown_to_html(text: str) -> str:
    """Convert basic Markdown tags (**bold**, *italics*, bullet points) to HTML

    safe for ReportLab Paragraph styling.
    """
    if not text:
        return ""
    # Convert bold
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    # Convert italic
    text = re.sub(r"\*(.*?)\*", r"<i>\1</i>", text)
    # Clean leading whitespace/bullet characters
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Restore the <b> and <i> tags that were escaped
    text = text.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>")
    text = text.replace("&lt;i&gt;", "<i>").replace("&lt;/i&gt;", "</i>")
    return text.strip()


# ---------------------------------------------------------------------------
# PDF Generation Orchestrator
# ---------------------------------------------------------------------------

def export_pdf(result: dict) -> bytes:
    """Build and return a corporate executive PDF report."""
    buffer = BytesIO()

    # Document margins: Top/Bottom margins set to 72 (1 inch) to leave room
    # for header/footer rules without overlapping body text.
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=72,
        bottomMargin=72,
    )
    story = []

    styles = getSampleStyleSheet()

    # Color Palette: Corporate Navy, Cool Slate, Accent Rose/Pink
    primary_color   = colors.HexColor("#1e1b4b") # Deep Indigo
    secondary_color = colors.HexColor("#4f46e5") # Electric Indigo
    text_color      = colors.HexColor("#0f172a") # Dark Slate Text
    muted_color     = colors.HexColor("#475569") # Slate Grey

    # Styles Definitions
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=26,
        leading=32,
        textColor=primary_color,
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "DocSubTitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=secondary_color,
        spaceAfter=15,
    )
    h1_style = ParagraphStyle(
        "H1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=primary_color,
        spaceBefore=18,
        spaceAfter=10,
        keepWithNext=True,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=15,
        textColor=text_color,
        spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14.5,
        textColor=text_color,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=8,
    )

    # ── Executive Cover Header ────────────────────────────────────────────────
    # A colored left-accent block using a single-cell ReportLab table
    header_content = [
        Paragraph("<b>EXECUTIVE DATA ANALYSIS REPORT</b>", title_style),
        Paragraph("Autonomous Business Intelligence & Strategy Recommendations", subtitle_style),
    ]
    header_table = Table([[header_content]], colWidths=[504])
    header_table.setStyle(
        TableStyle(
            [
                ("LINELEFT", (0, 0), (0, -1), 4, secondary_color),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(header_table)
    story.append(Spacer(1, 15))

    # ── Dataset summary callout box (McKinsey Style) ─────────────────────────
    df = result.get("dataframe")
    if df is not None:
        summary_title_style = ParagraphStyle(
            "SumTitle",
            parent=body_style,
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=primary_color,
        )
        summary_val_style = ParagraphStyle(
            "SumVal", parent=body_style, fontName="Helvetica", fontSize=10
        )

        columns_preview = f"{', '.join(df.columns[:8])}{'...' if len(df.columns) > 8 else ''}"

        # Clean structured layout inside a grey/indigo bordered box
        box_data = [
            [
                Paragraph("<b>Dataset Summary</b>", summary_title_style),
                Paragraph("", summary_val_style),
            ],
            [Paragraph("Total Records Analyzed", body_style), Paragraph(f"<b>{df.shape[0]:,}</b>", body_style)],
            [Paragraph("Total Attributes (Columns)", body_style), Paragraph(f"<b>{df.shape[1]}</b>", body_style)],
            [Paragraph("Target Columns Featured", body_style), Paragraph(columns_preview, body_style)],
        ]
        summary_box = Table(box_data, colWidths=[160, 320])
        summary_box.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")), # soft slate bg
                    ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),      # light border
                    ("LINEBELOW", (0, 0), (-1, 0), 1.5, secondary_color),         # blue accent bar under title
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("LEFTPADDING", (0, 0), (-1, -1), 12),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )
        story.append(summary_box)
    story.append(Spacer(1, 15))

    # ── Cleaning steps ────────────────────────────────────────────────────────
    story.append(Paragraph("Data Cleaning Audit Trail", h1_style))
    cleaning_text = result.get("cleaning_steps", "")
    if cleaning_text.strip():
        for raw in cleaning_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if line:
                formatted_line = _format_markdown_to_html(line)
                story.append(Paragraph(f"✔ &nbsp; {formatted_line}", bullet_style))
    else:
        story.append(Paragraph("No cleaning operations required. Dataset structure was validated as pristine.", body_style))
    story.append(Spacer(1, 10))

    # ── Relations ─────────────────────────────────────────────────────────────
    story.append(Paragraph("Key Correlation & Relationship Map", h1_style))
    relations_text = result.get("relations", "")
    if relations_text.strip():
        for raw in relations_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if line:
                formatted_line = _format_markdown_to_html(line)
                story.append(Paragraph(f"🔗 &nbsp; {formatted_line}", bullet_style))
    else:
        story.append(Paragraph("No significant correlations detected.", body_style))
    story.append(Spacer(1, 10))

    # ── Key insights (McKinsey style cards) ──────────────────────────────────
    story.append(Paragraph("Strategic Business Insights", h1_style))
    insights_text = result.get("insights", "")
    if insights_text.strip():
        # Parse and format the insights block cleanly
        insight_items = re.split(r"\d+\.\s+", insights_text)
        insight_count = 0
        for item in insight_items:
            item = item.strip()
            if not item:
                continue
            insight_count += 1

            # Convert markdown tags to HTML
            formatted_item = _format_markdown_to_html(item)

            # Split Observation / Business Implication / Actionable Strategy
            # so we can render them with custom bullet formats.
            parts = formatted_item.split("<br/>")
            if len(parts) < 2:
                # fall back to splitting by double linebreaks or raw newlines if standard spacing failed
                parts = formatted_item.split("\n")

            card_content = []
            for part in parts:
                part = part.strip()
                if not part:
                    continue
                # Highlight and indent subcategories
                if "Observation:" in part or "<b>Observation:</b>" in part:
                    card_content.append(Paragraph(part, body_style))
                elif "Implication:" in part or "<b>Implication:</b>" in part or "Business Implication" in part:
                    card_content.append(Paragraph(f"<font color='#475569'><i>{part}</i></font>", body_style))
                elif "Strategy:" in part or "<b>Strategy:</b>" in part or "Actionable Strategy" in part:
                    card_content.append(Paragraph(f"<font color='#4f46e5'><b>{part}</b></font>", body_style))
                else:
                    card_content.append(Paragraph(part, body_style))

            card_table = Table([[card_content]], colWidths=[504])
            card_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                        ("LINELEFT", (0, 0), (0, -1), 3, colors.HexColor("#6366f1")), # Indigo left bar
                        ("LEFTPADDING", (0, 0), (-1, -1), 12),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                        ("TOPPADDING", (0, 0), (-1, -1), 6),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                    ]
                )
            )
            story.append(Paragraph(f"<b>Insight {insight_count}</b>", ParagraphStyle("InsightLbl", parent=body_style, fontName="Helvetica-Bold", fontSize=11, textColor=primary_color, spaceBefore=4, spaceAfter=2)))
            story.append(card_table)
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph("No business insights generated.", body_style))

    # ── Visualizations (Clean structured presentation) ──────────────────────
    output_dir = result.get("output_dir", Path("outputs"))
    png_files  = list(Path(output_dir).glob("*.png"))

    if png_files:
        story.append(PageBreak())
        story.append(Paragraph("Visualized Business Intelligence", h1_style))
        story.append(Paragraph("The following charts display visual proof of the relationships mapped by the agents.", body_style))
        story.append(Spacer(1, 10))

        for png_file in png_files:
            try:
                # Dynamically scale to fit page margins (max width = 480pt)
                with PILImage.open(png_file) as img:
                    orig_w, orig_h = img.size
                max_w, max_h = 460, 280
                aspect = orig_h / orig_w
                if aspect > (max_h / max_w):
                    new_h = max_h
                    new_w = new_h / aspect
                else:
                    new_w = max_w
                    new_h = new_w * aspect

                title_p = Paragraph(f"<b>Figure: {png_file.stem}</b>", ParagraphStyle("FigTitle", parent=body_style, fontName="Helvetica-Bold", textColor=primary_color, spaceBefore=12, spaceAfter=6, keepWithNext=True))

                # Wrap visual inside a clean, centered container table
                img_flow = Image(str(png_file), width=new_w, height=new_h)
                img_table = Table([[img_flow]], colWidths=[480])
                img_table.setStyle(
                    TableStyle(
                        [
                            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                            ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                            ("TOPPADDING", (0, 0), (-1, -1), 8),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                        ]
                    )
                )

                story.append(title_p)
                story.append(img_table)
                story.append(Spacer(1, 15))
            except Exception as e:
                story.append(
                    Paragraph(f"Error loading image {png_file.name}: {e}", body_style)
                )
    else:
        pass  # Skip viz section if no pngs

    # Build the document using the NumberedCanvas for professional numbering
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


# ---------------------------------------------------------------------------
# Streamlit Caching Wrapper
# ---------------------------------------------------------------------------

@st.cache_data(show_spinner=False)
def export_pdf_cached(cache_key: str, result_cleaning: str, result_relations: str,
                      result_insights: str, result_code: str,
                      output_dir_str: str, df_csv: str) -> bytes:
    """Cached wrapper — only rebuilds the PDF when result content actually changes."""
    import pandas as pd
    from io import StringIO
    df = pd.read_csv(StringIO(df_csv))
    result = {
        "dataframe":     df,
        "cleaning_steps": result_cleaning,
        "relations":      result_relations,
        "insights":       result_insights,
        "code":           result_code,
        "output_dir":     output_dir_str,
    }
    return export_pdf(result)
