# Crewlyze
# Copyright (c) 2025 Sowmiyan S
# Licensed under the MIT License

"""
PDF export — world-class executive report format.
Premium design with:
  - Cinematic cover page with gradient header band and Crewlyze branding
  - Table of Contents page
  - Numbered section headers with coloured icon chips
  - Three-panel insight cards (Observation | Business Implication | Actionable Strategy)
  - Chart thumbnails embedded inline below each insight
  - Professional correlation tables with alternating bands
  - Data statistics tables with conditional number formatting
  - Styled risk alert boxes
  - Polished chat-log format with role badges and timestamps
  - Two-pass page-number canvas with company footer rule
"""

import html
import io
import os
import re
import urllib.parse
from datetime import datetime
from io import BytesIO
from pathlib import Path

import pandas as pd
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)


# ─────────────────────────────────────────────────────────────────────────────
# Colour palette
# ─────────────────────────────────────────────────────────────────────────────
C_CRIMSON      = colors.HexColor("#c0392b")   # primary accent
C_CRIMSON_DARK = colors.HexColor("#7b1d1d")   # dark crimson for headings
C_CRIMSON_PALE = colors.HexColor("#fff0f0")   # very light rose tint
C_AMBER        = colors.HexColor("#d97706")   # warning amber
C_AMBER_PALE   = colors.HexColor("#fffbeb")
C_EMERALD      = colors.HexColor("#047857")   # strategy green
C_EMERALD_PALE = colors.HexColor("#ecfdf5")
C_SAPPHIRE     = colors.HexColor("#1d4ed8")   # observation blue
C_SAPPHIRE_PALE= colors.HexColor("#eff6ff")
C_INK          = colors.HexColor("#0f172a")   # body text
C_MUTED        = colors.HexColor("#475569")   # secondary text
C_BORDER       = colors.HexColor("#cbd5e1")
C_LIGHT_GRID   = colors.HexColor("#e2e8f0")
C_ROW_ALT      = colors.HexColor("#f8fafc")
C_WHITE        = colors.white
C_COVER_BG     = colors.HexColor("#100608")   # near-black cover bg
C_COVER_BAND   = colors.HexColor("#8b0000")   # deep red band


# ─────────────────────────────────────────────────────────────────────────────
# Two-Pass Canvas — Page X of Y + corporate rules
# ─────────────────────────────────────────────────────────────────────────────

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas that renders running headers, footers, and page numbers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_decorations(total)
            super().showPage()
        super().save()

    def _draw_decorations(self, total_pages: int):
        self.saveState()
        page_num = self._pageNumber

        if page_num == 1:
            # Draw double 4-side executive decorative border around Cover Page
            self.setStrokeColor(C_CRIMSON_DARK)
            self.setLineWidth(2.0)
            self.rect(28, 28, 612 - 56, 792 - 56)

            self.setStrokeColor(C_AMBER)
            self.setLineWidth(0.75)
            self.rect(34, 34, 612 - 68, 792 - 68)

            # Draw 4 decorative corner caps
            for x, y in [(34, 34), (612 - 34, 34), (34, 792 - 34), (612 - 34, 792 - 34)]:
                self.setFillColor(C_CRIMSON_DARK)
                self.circle(x, y, 3.5, fill=1, stroke=0)

            self.restoreState()
            return

        # Crewlyze wordmark — always top-left
        self.setFillColor(C_CRIMSON)
        self.setFont("Helvetica-Bold", 9)
        self.drawString(54, 756, "CREWLYZE")

        # ── Running header ──────────────────────────────────────────────────
        self.setStrokeColor(C_BORDER)
        self.setLineWidth(0.5)
        self.line(54, 748, 558, 748)
        self.setFont("Helvetica", 7.5)
        self.setFillColor(C_MUTED)
        self.drawRightString(558, 753, "EXECUTIVE ANALYSIS REPORT  ·  CONFIDENTIAL")

        # ── Footer rule ─────────────────────────────────────────────────────
        self.line(54, 62, 558, 62)
        self.setFont("Helvetica", 7.5)
        self.setFillColor(C_MUTED)
        self.drawString(54, 50, "Generated by Crewlyze  ·  Powered by CrewAI")
        self.drawRightString(558, 50, f"Page {page_num} of {total_pages}")

        self.restoreState()


# ─────────────────────────────────────────────────────────────────────────────
# Markdown → ReportLab HTML helpers
# ─────────────────────────────────────────────────────────────────────────────

def _md_to_html(text: str) -> str:
    """Convert minimal markdown (**bold**, *italic*, `code`) to ReportLab-safe HTML."""
    if not text:
        return ""
    # 1. Strip AI reasoning artifacts first
    text = _clean_ai_artifacts(text)
    # 2. Escape raw HTML entities to prevent ReportLab Expat XML errors
    text = html.escape(str(text))
    # 3. Restore intended markdown formatting into safe ReportLab HTML tags
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"\*(.*?)\*",     r"<i>\1</i>", text)
    text = re.sub(r"`(.*?)`",       r"<font name=\"Courier\">\1</font>", text)
    return text.strip()


def _clean_ai_artifacts(text: str) -> str:
    """Strip AI reasoning tags (<think>...</think>) and system prefixes from raw text."""
    if not text:
        return ""
    # Strip full <think>...</think> blocks
    cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL | re.IGNORECASE)
    cleaned = re.sub(r'</?think>', '', cleaned, flags=re.IGNORECASE)
    lines = cleaned.split("\n")
    filtered = []
    for line in lines:
        stripped = line.strip()
        if re.match(r"^(thought|action|observation|route|call|api_key|response):\s*", stripped, re.IGNORECASE):
            continue
        filtered.append(line)
    return "\n".join(filtered).strip()


def _escape(text: str) -> str:
    """HTML-escape a plain string for safe inclusion in ReportLab Paragraphs."""
    return html.escape(str(text)) if text else ""


# ─────────────────────────────────────────────────────────────────────────────
# Insight / relation parsers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_insight_fields(text: str) -> dict:
    """Extract Observation, Business Implication, and Actionable Strategy."""
    text_clean = _clean_ai_artifacts(text)
    obs = imp = strat = ""

    obs_m   = re.search(r"\*\*Observation\*\*:\s*(.*?)(?=\*\*Business Implication\*\*|\*\*Actionable Strategy\*\*|$)", text_clean, re.DOTALL | re.IGNORECASE)
    imp_m   = re.search(r"\*\*Business Implication\*\*:\s*(.*?)(?=\*\*Observation\*\*|\*\*Actionable Strategy\*\*|$)", text_clean, re.DOTALL | re.IGNORECASE)
    strat_m = re.search(r"\*\*Actionable Strategy\*\*:\s*(.*?)(?=\*\*Observation\*\*|\*\*Business Implication\*\*|$)", text_clean, re.DOTALL | re.IGNORECASE)

    if obs_m:   obs   = obs_m.group(1).strip()
    if imp_m:   imp   = imp_m.group(1).strip()
    if strat_m: strat = strat_m.group(1).strip()

    # Loose fallbacks without asterisks
    if not obs:
        m = re.search(r"Observation:\s*(.*?)(?=Business Implication|Actionable Strategy|$)", text_clean, re.DOTALL | re.IGNORECASE)
        if m: obs = m.group(1).strip()
    if not imp:
        m = re.search(r"Business Implication:\s*(.*?)(?=Observation|Actionable Strategy|$)", text_clean, re.DOTALL | re.IGNORECASE)
        if m: imp = m.group(1).strip()
    if not strat:
        m = re.search(r"Actionable Strategy:\s*(.*?)(?=Observation|Business Implication|$)", text_clean, re.DOTALL | re.IGNORECASE)
        if m: strat = m.group(1).strip()

    return {
        "observation": obs or text_clean,
        "implication": imp,
        "strategy":    strat,
    }


def _parse_relation_line(line: str) -> dict:
    parts = [p.strip() for p in line.split("|")]
    res   = {"x": "N/A", "y": "N/A", "type": "N/A", "details": "N/A"}
    for part in parts:
        if ":" in part:
            key, val = part.split(":", 1)
            key = key.strip().lower()
            val = val.strip()
            if   key == "x":       res["x"]       = val
            elif key == "y":       res["y"]       = val
            elif key == "type":    res["type"]    = val
            elif key == "details": res["details"] = val
        else:
            pc = part.lstrip("- ").strip()
            if pc:
                res["details"] = pc
    return res


def _find_matching_chart(insight_text: str, png_files: list, placed: set):
    text_lower = insight_text.lower()
    for png in png_files:
        if png in placed:
            continue
        stem = png.stem.lower().replace("_", " ")
        words = [w for w in stem.split()
                 if w not in ("vs", "plot", "chart", "scatter", "bar",
                               "box", "line", "distribution", "correlation", "plotly")]
        if words and all(w in text_lower for w in words):
            return png
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Number formatting
# ─────────────────────────────────────────────────────────────────────────────

def _fmt_num(val) -> str:
    try:
        if pd.isna(val):
            return "—"
        f = float(val)
        if f.is_integer():
            return f"{int(f):,}"
        if abs(f) < 0.0001 and f != 0:
            return f"{f:.4e}"
        s = f"{f:,.2f}".rstrip("0").rstrip(".")
        return s
    except Exception:
        return str(val)


# ─────────────────────────────────────────────────────────────────────────────
# Reusable layout primitives
# ─────────────────────────────────────────────────────────────────────────────

def _section_header(number: str, title: str, body_style) -> Table:
    """Premium numbered section header with left crimson chip + uppercase title."""
    chip_style = ParagraphStyle(
        "ChipNum", fontName="Helvetica-Bold", fontSize=9,
        textColor=C_WHITE, alignment=1, leading=11
    )
    title_style = ParagraphStyle(
        "SectTitle", fontName="Helvetica-Bold", fontSize=13,
        textColor=C_INK, leading=16, leftIndent=0
    )
    chip = Paragraph(number, chip_style)
    heading = Paragraph(title.upper(), title_style)

    tbl = Table([[chip, heading]], colWidths=[24, 476])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, 0), C_CRIMSON),
        ("BACKGROUND",    (1, 0), (1, 0), colors.HexColor("#fafafa")),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (0, 0),  0),
        ("LEFTPADDING",   (1, 0), (1, 0), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ("LINEBELOW",     (0, 0), (-1, -1), 1.5, C_CRIMSON),
    ]))
    return tbl


def _kv_chip(label: str, value: str, label_style, value_style) -> Table:
    """Compact key-value pair rendered in two cells."""
    return Table(
        [[Paragraph(f"<b>{label}</b>", label_style), Paragraph(_escape(value), value_style)]],
        colWidths=[130, 370]
    )


def _img_flowable(png_path: Path, max_w: int = 440, max_h: int = 250):
    """Return (img_table, fig_title) for a chart image, or (None, None) on error."""
    try:
        with PILImage.open(png_path) as im:
            ow, oh = im.size
        aspect = oh / ow
        if aspect > (max_h / max_w):
            nh, nw = max_h, max_h / aspect
        else:
            nw, nh = max_w, max_w * aspect

        img_flow  = Image(str(png_path), width=nw, height=nh)
        img_table = Table([[img_flow]], colWidths=[504])
        img_table.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("BOX",           (0, 0), (-1, -1), 0.75, C_BORDER),
            ("BACKGROUND",    (0, 0), (-1, -1), C_WHITE),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        fig_title = Paragraph(
            f"<i>Figure: {png_path.stem.replace('_', ' ').title()}</i>",
            ParagraphStyle("FigCap", fontName="Helvetica-Oblique", fontSize=7.5,
                           textColor=C_MUTED, spaceBefore=3, spaceAfter=2, alignment=1)
        )
        return img_table, fig_title
    except Exception:
        return None, None


# ─────────────────────────────────────────────────────────────────────────────
# Column statistics table
# ─────────────────────────────────────────────────────────────────────────────

def _build_stats_tables(df: pd.DataFrame, body_style) -> list:
    flowables = []

    hdr_style = ParagraphStyle("TblHdr", fontName="Helvetica-Bold", fontSize=8.5,
                               textColor=C_WHITE, leading=11)
    cell_style = ParagraphStyle("TblCell", fontName="Helvetica", fontSize=8.5,
                                textColor=C_INK, leading=12)

    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    cat_cols     = df.select_dtypes(include=["object", "category"]).columns.tolist()

    if numeric_cols:
        header = [
            Paragraph("<b>Column</b>",   hdr_style),
            Paragraph("<b>Min</b>",      hdr_style),
            Paragraph("<b>Max</b>",      hdr_style),
            Paragraph("<b>Mean</b>",     hdr_style),
            Paragraph("<b>Median</b>",   hdr_style),
            Paragraph("<b>Std Dev</b>",  hdr_style),
            Paragraph("<b>Missing%</b>", hdr_style),
        ]
        rows = [header]
        for col in numeric_cols[:22]:
            s   = df[col]
            sn  = s.dropna()
            miss = round(s.isnull().sum() / max(len(df), 1) * 100, 1)
            rows.append([
                Paragraph(_escape(str(col)),                                  cell_style),
                Paragraph(_fmt_num(sn.min())    if not sn.empty else "—",     cell_style),
                Paragraph(_fmt_num(sn.max())    if not sn.empty else "—",     cell_style),
                Paragraph(_fmt_num(sn.mean())   if not sn.empty else "—",     cell_style),
                Paragraph(_fmt_num(sn.median()) if not sn.empty else "—",     cell_style),
                Paragraph(_fmt_num(sn.std())    if len(sn) > 1 else "—",      cell_style),
                Paragraph(f"{miss}%",                                          cell_style),
            ])

        tbl = Table(rows, colWidths=[130, 52, 52, 52, 52, 52, 58])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  C_CRIMSON_DARK),
            ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_LIGHT_GRID),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_ROW_ALT]),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        flowables.extend([tbl, Spacer(1, 10)])

    if cat_cols:
        cat_hdr = [
            Paragraph("<b>Column</b>",             hdr_style),
            Paragraph("<b>Top Values (count)</b>", hdr_style),
            Paragraph("<b>Unique</b>",             hdr_style),
            Paragraph("<b>Missing%</b>",           hdr_style),
        ]
        cat_rows = [cat_hdr]
        for col in cat_cols[:10]:
            s    = df[col]
            miss = round(s.isnull().sum() / max(len(df), 1) * 100, 1)
            top3 = s.value_counts().head(3)
            top_str = ", ".join(f"{_escape(str(v))}({c})" for v, c in top3.items()) if not top3.empty else "—"
            cat_rows.append([
                Paragraph(_escape(str(col)), cell_style),
                Paragraph(top_str[:100],     cell_style),
                Paragraph(str(s.nunique()),  cell_style),
                Paragraph(f"{miss}%",        cell_style),
            ])

        cat_tbl = Table(cat_rows, colWidths=[110, 278, 56, 56])
        cat_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  C_CRIMSON_DARK),
            ("BOX",           (0, 0), (-1, -1), 0.5, C_BORDER),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_LIGHT_GRID),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_ROW_ALT]),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        flowables.append(cat_tbl)

    return flowables


# ─────────────────────────────────────────────────────────────────────────────
# Main Executive PDF generator
# ─────────────────────────────────────────────────────────────────────────────

def export_pdf(result: dict, filename: str = "") -> bytes:
    """Build and return a premium world-class executive PDF report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54, leftMargin=54,
        topMargin=82, bottomMargin=82,
    )

    story  = []
    styles = getSampleStyleSheet()

    # Shared paragraph styles
    body_style = ParagraphStyle("Body", fontName="Helvetica", fontSize=9.5,
                                leading=14.5, textColor=C_INK, spaceAfter=5)
    small_style = ParagraphStyle("Small", fontName="Helvetica", fontSize=8.5,
                                 leading=13, textColor=C_MUTED)
    h2_style = ParagraphStyle("H2", fontName="Helvetica-Bold", fontSize=10.5,
                               leading=14, textColor=C_CRIMSON_DARK,
                               spaceBefore=10, spaceAfter=4, keepWithNext=True)
    bullet_style = ParagraphStyle("Bullet", fontName="Helvetica", fontSize=9.5,
                                  leading=14.5, textColor=C_INK,
                                  leftIndent=14, firstLineIndent=-10, spaceAfter=5)
    label_style = ParagraphStyle("MetaKey", fontName="Helvetica-Bold", fontSize=8,
                                 textColor=C_MUTED, leading=11)
    value_style = ParagraphStyle("MetaVal", fontName="Helvetica", fontSize=9,
                                 textColor=C_INK, leading=13)

    # ── Pull result data ──────────────────────────────────────────────────────
    raw_insights   = _clean_ai_artifacts(result.get("insights", "")).strip()
    cleaning_text  = _clean_ai_artifacts(result.get("cleaning_steps", "")).strip()
    relations_text = _clean_ai_artifacts(result.get("relations", "")).strip()
    report_title   = _clean_ai_artifacts(result.get("report_title") or result.get("name") or filename or "Executive Analysis").strip()
    report_goal    = _clean_ai_artifacts(result.get("goal", "")).strip()
    timestamp      = datetime.now().strftime("%B %d, %Y  ·  %I:%M %p")
    df             = result.get("dataframe")
    output_dir     = result.get("output_dir", Path("outputs"))
    png_files      = list(Path(output_dir).glob("*.png"))
    placed_charts  = set()

    # ── Parse insight subsections ─────────────────────────────────────────────
    objectives_text = stats_text = strategic_text = warnings_text = ""
    if raw_insights:
        for sec in re.split(r"###\s+", raw_insights):
            lines = sec.split("\n")
            if not lines or not lines[0].strip():
                continue
            hdr     = lines[0].strip().lower()
            content = "\n".join(lines[1:]).strip()
            if   "objective" in hdr or "goal" in hdr: objectives_text = content
            elif "stat"      in hdr:                   stats_text      = content
            elif "insight"   in hdr:                   strategic_text  = content
            elif "warning"   in hdr or "alert" in hdr: warnings_text   = content
        if not strategic_text and not objectives_text:
            strategic_text = raw_insights

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 1 — COVER
    # ═══════════════════════════════════════════════════════════════════════════

    # Top Header Pill / Brand Tag
    story.append(Spacer(1, 50))
    story.append(Paragraph(
        "CREWLYZE EXECUTIVE ANALYSIS",
        ParagraphStyle("CoverBadge", fontName="Helvetica-Bold", fontSize=9,
                       leading=12, textColor=C_CRIMSON_DARK, alignment=1)
    ))
    story.append(Spacer(1, 25))

    # Title (dynamic, generated by LLM)
    story.append(Paragraph(
        f"<b>{_escape(report_title.upper())}</b>",
        ParagraphStyle("CoverTitle", fontName="Helvetica-Bold", fontSize=26,
                       leading=34, textColor=C_CRIMSON_DARK, spaceAfter=15, alignment=1)
    ))
    story.append(Spacer(1, 10))

    story.append(HRFlowable(width="60%", thickness=1.5, color=C_CRIMSON, spaceBefore=10, spaceAfter=20, hAlign='CENTER'))

    # Subtitle / Generation timestamp (dynamic)
    story.append(Paragraph(
        f"Autonomous Agentic Intelligence &amp; Data Audit Report<br/>"
        f"<font color='#64748b' size=9.5>Generated on {timestamp}</font>",
        ParagraphStyle("CoverDate", fontName="Helvetica", fontSize=11,
                       leading=18, textColor=C_INK, alignment=1)
    ))

    story.append(Spacer(1, 60))

    # Dataset Summary Card on Cover Page
    if df is not None and isinstance(df, pd.DataFrame):
        cover_meta_data = [
            [Paragraph("<b>TOTAL RECORDS</b>", label_style), Paragraph(f"<b>{df.shape[0]:,}</b>", value_style),
             Paragraph("<b>TOTAL COLUMNS</b>", label_style), Paragraph(f"<b>{df.shape[1]}</b>", value_style)],
            [Paragraph("<b>NUMERIC COLS</b>", label_style), Paragraph(f"<b>{len(df.select_dtypes(include=['number']).columns)}</b>", value_style),
             Paragraph("<b>CATEGORICAL COLS</b>", label_style), Paragraph(f"<b>{len(df.select_dtypes(include=['object', 'category']).columns)}</b>", value_style)]
        ]
        t_cover = Table(cover_meta_data, colWidths=[110, 110, 110, 110])
        t_cover.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), C_CRIMSON_PALE),
            ("BOX", (0, 0), (-1, -1), 1, C_CRIMSON),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, C_BORDER),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(t_cover)

    story.append(Spacer(1, 40))
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 2 — EXECUTIVE SUMMARY & DATASET OVERVIEW
    # ═══════════════════════════════════════════════════════════════════════════

    story.append(KeepTogether([
        _section_header("01", "Executive Summary & Dataset Overview", body_style),
        Spacer(1, 12)
    ]))

    story.append(Paragraph(
        "This report presents high-value strategic recommendations, data quality audit trails, "
        "correlation mappings, and chart-backed insights generated autonomously from the uploaded dataset.",
        body_style
    ))
    story.append(Spacer(1, 10))

    if df is not None and isinstance(df, pd.DataFrame):
        ncol = len(df.select_dtypes(include=["number"]).columns)
        ccol = len(df.select_dtypes(include=["object", "category"]).columns)
        cols_preview = ", ".join(str(c) for c in df.columns[:7])
        if len(df.columns) > 7:
            cols_preview += "  …"

        kv_rows = [
            [Paragraph("<b>Total Records</b>",    label_style), Paragraph(f"<b>{df.shape[0]:,}</b>", value_style),
             Paragraph("<b>Total Columns</b>",    label_style), Paragraph(f"<b>{df.shape[1]}</b>",   value_style)],
            [Paragraph("<b>Numeric Columns</b>",  label_style), Paragraph(f"<b>{ncol}</b>",           value_style),
             Paragraph("<b>Categorical Cols</b>", label_style), Paragraph(f"<b>{ccol}</b>",           value_style)],
            [Paragraph("<b>Column Preview</b>",   label_style), Paragraph(_escape(cols_preview),      value_style),
             Paragraph("", label_style), Paragraph("", value_style)],
        ]
        kv_tbl = Table(kv_rows, colWidths=[100, 152, 100, 152])
        kv_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), C_ROW_ALT),
            ("BOX",           (0, 0), (-1, -1), 1, C_BORDER),
            ("LINEBELOW",     (0, 0), (-1, 0),  1.5, C_CRIMSON),
            ("INNERGRID",     (0, 0), (-1, -1), 0.25, C_LIGHT_GRID),
            ("TOPPADDING",    (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(kv_tbl)
        story.append(Spacer(1, 18))

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 3+ — STRATEGIC BUSINESS INSIGHTS
    # ═══════════════════════════════════════════════════════════════════════════

    if strategic_text:
        story.append(KeepTogether([
            _section_header("02", "Strategic Business Insights", body_style),
            Spacer(1, 12)
        ]))
        story.append(Paragraph(
            "Each insight card below contains three panels: the raw data <b>Observation</b>, "
            "its derived <b>Business Implication</b>, and a concrete <b>Actionable Strategy</b>.",
            body_style
        ))
        story.append(Spacer(1, 10))

        hdr_obs   = ParagraphStyle("HObs",   fontName="Helvetica-Bold", fontSize=8.5, textColor=C_SAPPHIRE, leading=12)
        hdr_imp   = ParagraphStyle("HImp",   fontName="Helvetica-Bold", fontSize=8.5, textColor=colors.HexColor("#6d28d9"), leading=12)
        hdr_strat = ParagraphStyle("HStrat", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_EMERALD,  leading=12)
        cell_obs   = ParagraphStyle("CObs",  fontName="Helvetica", fontSize=8.5, textColor=C_INK, leading=13)
        cell_imp   = ParagraphStyle("CImp",  fontName="Helvetica", fontSize=8.5, textColor=C_INK, leading=13)
        cell_strat = ParagraphStyle("CStrt", fontName="Helvetica", fontSize=8.5, textColor=C_INK, leading=13)

        insight_items = re.split(r"\d+\.\s+", strategic_text)
        insight_count = 0

        for raw_item in insight_items:
            item = raw_item.strip()
            if not item:
                continue
            insight_count += 1
            fields = _parse_insight_fields(item)

            # Extract title from first bold token
            title = ""
            first = item.split("\n")[0].strip()
            if first and not any(k in first for k in ("Observation", "Implication", "Strategy")):
                title = first.replace("**", "").replace("<b>", "").replace("</b>", "").strip()

            # ── Insight label ──────────────────────────────────────────────
            lbl_text = f"<b>#{insight_count}  {_escape(title)}</b>" if title else f"<b>Insight #{insight_count}</b>"
            lbl = Paragraph(
                lbl_text,
                ParagraphStyle("InsLbl", fontName="Helvetica-Bold", fontSize=10.5,
                               textColor=C_CRIMSON_DARK, spaceBefore=12,
                               spaceAfter=5, keepWithNext=True)
            )

            # ── Three-panel card ───────────────────────────────────────────
            card_data = [
                [
                    Paragraph("<b>📊  Observation</b>",        hdr_obs),
                    Paragraph("<b>💡  Business Implication</b>", hdr_imp),
                    Paragraph("<b>🎯  Actionable Strategy</b>",  hdr_strat),
                ],
                [
                    Paragraph(_md_to_html(fields["observation"]),              cell_obs),
                    Paragraph(_md_to_html(fields["implication"] or "—"),       cell_imp),
                    Paragraph(_md_to_html(fields["strategy"]    or "—"),       cell_strat),
                ],
            ]
            card = Table(card_data, colWidths=[160, 172, 172])
            card.setStyle(TableStyle([
                # Header row backgrounds
                ("BACKGROUND",    (0, 0), (0, 0), C_SAPPHIRE_PALE),
                ("BACKGROUND",    (1, 0), (1, 0), colors.HexColor("#f5f3ff")),
                ("BACKGROUND",    (2, 0), (2, 0), C_EMERALD_PALE),
                # Data row backgrounds
                ("BACKGROUND",    (0, 1), (0, 1), colors.HexColor("#f0f8ff")),
                ("BACKGROUND",    (1, 1), (1, 1), colors.HexColor("#fdfaff")),
                ("BACKGROUND",    (2, 1), (2, 1), colors.HexColor("#f0fff8")),
                # Borders
                ("BOX",           (0, 0), (-1, -1), 0.75, C_BORDER),
                ("INNERGRID",     (0, 0), (-1, -1), 0.4,  C_LIGHT_GRID),
                ("LINEBELOW",     (0, 0), (-1, 0),  1.2,  C_BORDER),
                ("VALIGN",        (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING",    (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("LEFTPADDING",   (0, 0), (-1, -1), 9),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 9),
            ]))

            story.append(KeepTogether([lbl, card]))

            # ── Paired chart ───────────────────────────────────────────────
            matched = _find_matching_chart(item, png_files, placed_charts)
            if matched:
                img_tbl, fig_cap = _img_flowable(matched)
                if img_tbl:
                    story.append(Spacer(1, 5))
                    story.append(KeepTogether([img_tbl, fig_cap]))
                    placed_charts.add(matched)
            story.append(Spacer(1, 14))

        story.append(Spacer(1, 8))

    # ── Risk alerts ────────────────────────────────────────────────────────────
    if warnings_text and "no warnings" not in warnings_text.lower() and "none" not in warnings_text.lower():
        story.append(KeepTogether([
            _section_header("03", "Business Risks & Critical Alerts", body_style),
            Spacer(1, 10)
        ]))
        warn_content = [Paragraph(
            _md_to_html(warnings_text).replace("\n", "<br/>"),
            ParagraphStyle("WarnBody", fontName="Helvetica", fontSize=9.5,
                           textColor=colors.HexColor("#7f1d1d"), leading=14)
        )]
        warn_tbl = Table([warn_content], colWidths=[504])
        warn_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), C_CRIMSON_PALE),
            ("LINELEFT",      (0, 0), (0, -1),  5, C_CRIMSON),
            ("BOX",           (0, 0), (-1, -1), 0.75, colors.HexColor("#fecaca")),
            ("LEFTPADDING",   (0, 0), (-1, -1), 14),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
            ("TOPPADDING",    (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(KeepTogether([warn_tbl, Spacer(1, 14)]))
        story.append(Spacer(1, 8))

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 4+ — DATA SUMMARY & METHODOLOGY
    # ═══════════════════════════════════════════════════════════════════════════

    sec_num = "04" if (strategic_text or warnings_text) else "03"
    story.append(KeepTogether([
        _section_header(sec_num, "Data Summary & Methodology", body_style),
        Spacer(1, 12)
    ]))

    if objectives_text:
        story.append(Paragraph("Project Objectives &amp; Scope", h2_style))
        story.append(Paragraph(
            _md_to_html(objectives_text).replace("\n", "<br/>"), body_style
        ))
        story.append(Spacer(1, 10))

    if cleaning_text:
        story.append(Paragraph("Data Cleaning Audit Trail", h2_style))
        story.append(Paragraph(
            "The following transformations were applied to the raw dataset during preprocessing:", body_style
        ))
        for raw in cleaning_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if line:
                story.append(Paragraph(f"▸  {_md_to_html(line)}", bullet_style))
        story.append(Spacer(1, 10))

    if relations_text:
        story.append(Paragraph("Key Correlation &amp; Relationship Map", h2_style))

        hdr_style_tbl = ParagraphStyle("RelHdr", fontName="Helvetica-Bold", fontSize=8.5,
                                       textColor=C_WHITE, leading=11)
        cell_r = ParagraphStyle("RelCell", fontName="Helvetica", fontSize=8.5,
                                textColor=C_INK, leading=12)

        desc_lines = []
        tbl_data = [[
            Paragraph("<b>Variable X</b>",             hdr_style_tbl),
            Paragraph("<b>Variable Y</b>",             hdr_style_tbl),
            Paragraph("<b>Chart Type</b>",             hdr_style_tbl),
            Paragraph("<b>Business Context</b>",       hdr_style_tbl),
        ]]

        for raw in relations_text.split("\n"):
            line = raw.strip().lstrip("-*• ").strip()
            if not line:
                continue
            if "|" in line or ("x:" in line.lower() and "y:" in line.lower()):
                parsed = _parse_relation_line(line)
                if parsed["x"] != "N/A" or parsed["y"] != "N/A":
                    # Filter out placeholders or templates
                    if "[" in parsed["x"] or "]" in parsed["x"] or "Column" in parsed["x"] or "Column" in parsed["y"]:
                        continue
                    tbl_data.append([
                        Paragraph(f"<b>{_escape(parsed['x'])}</b>", cell_r),
                        Paragraph(f"<b>{_escape(parsed['y'])}</b>", cell_r),
                        Paragraph(_escape(parsed["type"]),           cell_r),
                        Paragraph(_escape(parsed["details"]),        cell_r),
                    ])
                    continue
            if not any(line.lower().startswith(k) for k in ("strictly", "output nothing")):
                desc_lines.append(line)

        if desc_lines:
            story.append(Paragraph(
                "<br/>".join(_md_to_html(l) for l in desc_lines), body_style
            ))
            story.append(Spacer(1, 6))
        else:
            story.append(Paragraph(
                "The following variable pairs were identified for targeted visualization:", body_style
            ))
            story.append(Spacer(1, 4))

        if len(tbl_data) > 1:
            rel_tbl = Table(tbl_data, colWidths=[100, 100, 90, 214])
            rel_tbl.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0),  C_CRIMSON_DARK),
                ("BOX",           (0, 0), (-1, -1), 0.75, C_BORDER),
                ("INNERGRID",     (0, 0), (-1, -1), 0.3,  C_LIGHT_GRID),
                ("ROWBACKGROUNDS",(0, 1), (-1, -1), [C_WHITE, C_ROW_ALT]),
                ("VALIGN",        (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING",   (0, 0), (-1, -1), 8),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
            ]))
            story.append(KeepTogether([rel_tbl]))
            
        # Search for and render correlation mapping chart/heatmap directly inside Section 4
        corr_chart = None
        for png in png_files:
            p_name = png.name.lower()
            if "correlation" in p_name or "relation" in p_name or "matrix" in p_name:
                corr_chart = png
                break
        
        if corr_chart:
            img_tbl, fig_cap = _img_flowable(corr_chart)
            if img_tbl:
                story.append(Spacer(1, 10))
                story.append(KeepTogether([img_tbl, fig_cap]))
                placed_charts.add(corr_chart)
                
        story.append(Spacer(1, 14))

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 5+ — APPENDIX (Per-column stats + remaining charts)
    # ═══════════════════════════════════════════════════════════════════════════

    app_num = str(int(sec_num) + 1).zfill(2)
    story.append(KeepTogether([
        _section_header(app_num, "Appendix", body_style),
        Spacer(1, 12)
    ]))

    if df is not None and isinstance(df, pd.DataFrame):
        story.append(Paragraph("Per-Column Statistical Summary", h2_style))
        story.append(Paragraph(
            "Numeric distributions and categorical frequency breakdowns for all dataset columns:",
            body_style
        ))
        story.append(Spacer(1, 5))
        stat_flowables = _build_stats_tables(df, body_style)
        if stat_flowables:
            story.extend(stat_flowables)
        story.append(Spacer(1, 12))

    unplaced = [p for p in png_files if p not in placed_charts]
    if unplaced:
        story.append(Paragraph("Additional Analytical Visualizations", h2_style))
        story.append(Paragraph(
            "Supplementary visual mappings of auxiliary data relationships:", body_style
        ))
        story.append(Spacer(1, 8))
        for png_file in unplaced:
            img_tbl, fig_cap = _img_flowable(png_file)
            if img_tbl:
                fig_lbl = Paragraph(
                    f"<b>Figure: {_escape(png_file.stem.replace('_', ' ').title())}</b>",
                    ParagraphStyle("FigLbl", fontName="Helvetica-Bold", fontSize=9,
                                   textColor=C_CRIMSON_DARK, spaceBefore=8, spaceAfter=4, keepWithNext=True)
                )
                story.append(KeepTogether([fig_lbl, img_tbl, fig_cap, Spacer(1, 12)]))
            else:
                story.append(Paragraph(f"(Could not load: {png_file.name})", small_style))

    # ── Conclusion box ─────────────────────────────────────────────────────────
    conclusion_items = [
        Paragraph(
            "<b>Executive Conclusion &amp; Recommended Next Steps</b>",
            ParagraphStyle("ConclHdr", fontName="Helvetica-Bold", fontSize=11,
                           textColor=C_CRIMSON_DARK, spaceAfter=6, leading=14)
        ),
        Paragraph(
            (
                "Based on the analysis conducted on the dataset, the data pipeline has successfully validated "
                "and evaluated the provided records. "
                "The findings point towards the strategic recommendations detailed in the Insights section. "
                "To maximize value from these insights, it is highly recommended to prioritize the outlined "
                "Actionable Strategies, actively mitigate any Business Risks surfaced in this report, and leverage "
                "the key visualizations to communicate findings with stakeholders."
            ) if not strategic_text else (
                "Based on the autonomous data analysis, several critical patterns were uncovered. "
                f"Most notably, the primary insight reveals: {_escape(strategic_text.split('**Observation**:')[1].split('**Business Implication**:')[0].strip()[:250] if '**Observation**:' in strategic_text else strategic_text[:250])}... "
                "To maximize business value, stakeholders must prioritize the Actionable Strategies detailed in the Insights section, "
                "address the highlighted Business Risks, and use the provided data visualizations to drive informed decision-making."
            ),
            ParagraphStyle("ConclBody", fontName="Helvetica", fontSize=9.5,
                           textColor=C_INK, leading=14.5)
        ),
    ]
    concl_tbl = Table([[conclusion_items]], colWidths=[504])
    concl_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), C_ROW_ALT),
        ("BOX",           (0, 0), (-1, -1), 1,  C_BORDER),
        ("LINELEFT",      (0, 0), (0, -1),  5,  C_CRIMSON_DARK),
        ("LEFTPADDING",   (0, 0), (-1, -1), 16),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 16),
        ("TOPPADDING",    (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(Spacer(1, 18))
    story.append(KeepTogether([concl_tbl]))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


# ─────────────────────────────────────────────────────────────────────────────
# Cached wrapper
# ─────────────────────────────────────────────────────────────────────────────

_pdf_cache: dict = {}


def export_pdf_cached(
    cache_key:       str,
    filename:        str = "",
    result_cleaning: str = "",
    result_relations:str = "",
    result_insights: str = "",
    result_code:     str = "",
    output_dir_str:  str = "outputs",
    df_csv:          str = "",
) -> bytes:
    if cache_key in _pdf_cache:
        return _pdf_cache[cache_key]

    df = None
    if df_csv:
        try:
            df = pd.read_csv(io.StringIO(df_csv))
        except Exception:
            df = None

    result = {
        "dataframe":      df,
        "cleaning_steps": result_cleaning,
        "relations":      result_relations,
        "insights":       result_insights,
        "code":           result_code,
        "output_dir":     output_dir_str,
    }
    pdf_bytes = export_pdf(result, filename=filename)
    _pdf_cache[cache_key] = pdf_bytes
    return pdf_bytes


# ─────────────────────────────────────────────────────────────────────────────
# Chat log helpers
# ─────────────────────────────────────────────────────────────────────────────

def _clean_chat_content(text: str) -> str:
    if not text:
        return ""
    cleaned = re.sub(r'\[Auto-Healing system resolved a code error!\][\s\S]*?(?:Successful Execution Output:\s*(?:\(no output\)|\S+)?\s*)', '', text, flags=re.IGNORECASE)
    cleaned = re.sub(r'\[Auto-Healing system installed missing package[\s\S]*?(?:Output:\s*\S*\s*)?', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'Original Error:[\s\S]*?(?=(?:Successful Execution Output|$))', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'Successful Execution Output:\s*\(no output\)', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'Successful Execution Output:', '', cleaned, flags=re.IGNORECASE)
    return cleaned.strip()


# ─────────────────────────────────────────────────────────────────────────────
# Chat PDF generator — premium format
# ─────────────────────────────────────────────────────────────────────────────

def export_chat_pdf(messages: list, session_id: str) -> bytes:
    """Generate a premium styled PDF from a Crew Chat conversation."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=54, leftMargin=54,
        topMargin=82, bottomMargin=82,
    )
    styles = getSampleStyleSheet()

    P_RED      = colors.HexColor("#c0392b")
    P_DARK     = colors.HexColor("#7b1d1d")
    P_BLUE     = colors.HexColor("#1d4ed8")
    P_MUTED    = colors.HexColor("#475569")
    P_INK      = colors.HexColor("#0f172a")
    P_PALE_U   = colors.HexColor("#f0f4ff")
    P_PALE_A   = colors.HexColor("#fff5f5")
    P_BORDER   = colors.HexColor("#cbd5e1")

    title_style = ParagraphStyle("ChatTitle", fontName="Helvetica-Bold", fontSize=22,
                                  leading=26, textColor=P_DARK, spaceAfter=4)
    meta_style  = ParagraphStyle("ChatMeta",  fontName="Helvetica", fontSize=8.5,
                                  leading=12, textColor=P_MUTED, spaceAfter=8)
    user_style  = ParagraphStyle("UserMsg",   fontName="Helvetica", fontSize=9.5,
                                  leading=14.5, textColor=P_INK)
    asst_style  = ParagraphStyle("AsstMsg",   fontName="Helvetica", fontSize=9.5,
                                  leading=14.5, textColor=P_INK)
    role_u_style= ParagraphStyle("RoleU", fontName="Helvetica-Bold", fontSize=8,
                                  textColor=P_BLUE, leading=11)
    role_a_style= ParagraphStyle("RoleA", fontName="Helvetica-Bold", fontSize=8,
                                  textColor=P_RED,  leading=11)

    # Cover strip
    def _band(text, bg, fg):
        t = Table([[Paragraph(text, ParagraphStyle("B", fontName="Helvetica-Bold",
                               fontSize=8.5, textColor=fg, alignment=1, leading=11))]],
                  colWidths=[504], rowHeights=[20])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), bg),
            ("ALIGN",         (0,0),(-1,-1), "CENTER"),
            ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
            ("TOPPADDING",    (0,0),(-1,-1), 2),
            ("BOTTOMPADDING", (0,0),(-1,-1), 2),
        ]))
        return t

    def _divider_c(thick=2, color=P_RED):
        t = Table([[""]], colWidths=[504], rowHeights=[thick])
        t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),color),
                                ("TOPPADDING",(0,0),(-1,-1),0),
                                ("BOTTOMPADDING",(0,0),(-1,-1),0)]))
        return t

    story = [
        Spacer(1, 30),
        _band("CREW CHAT  ·  CONVERSATION EXPORT", P_DARK, colors.white),
        Spacer(1, 5),
        _divider_c(3),
        Spacer(1, 14),
        Paragraph("<b>Crew Chat Log</b>", title_style),
        Paragraph(
            f"Session ID: {session_id}  ·  Exported on {datetime.now().strftime('%d %B %Y at %I:%M %p')}",
            meta_style
        ),
        Spacer(1, 4),
        _divider_c(1, colors.HexColor("#e2e8f0")),
        Spacer(1, 16),
    ]

    for idx, msg in enumerate(messages, start=1):
        role      = msg.get("role", "user")
        content   = _clean_chat_content(msg.get("content", ""))
        plot_url  = msg.get("plot_url")
        is_user   = (role == "user")

        formatted = _md_to_html(content).replace("\n", "<br/>")

        if is_user:
            role_label = Paragraph("YOU", role_u_style)
            msg_para   = Paragraph(formatted, user_style)
            msg_tbl    = Table([[msg_para]], colWidths=[450])
            msg_tbl.setStyle(TableStyle([
                ("BACKGROUND",    (0,0),(-1,-1), P_PALE_U),
                ("BOX",           (0,0),(-1,-1), 0.5, P_BORDER),
                ("LINERIGHT",     (0,0),(-1,-1), 3,  P_BLUE),
                ("LEFTPADDING",   (0,0),(-1,-1), 12),
                ("RIGHTPADDING",  (0,0),(-1,-1), 12),
                ("TOPPADDING",    (0,0),(-1,-1), 9),
                ("BOTTOMPADDING", (0,0),(-1,-1), 9),
            ]))
            wrapper = Table([[role_label, ""], [msg_tbl, ""]], colWidths=[450, 54])
        else:
            role_label = Paragraph("CREW CHAT", role_a_style)
            msg_para   = Paragraph(formatted, asst_style)
            msg_tbl    = Table([[msg_para]], colWidths=[450])
            msg_tbl.setStyle(TableStyle([
                ("BACKGROUND",    (0,0),(-1,-1), P_PALE_A),
                ("BOX",           (0,0),(-1,-1), 0.5, P_BORDER),
                ("LINELEFT",      (0,0),(0,-1),  3,  P_RED),
                ("LEFTPADDING",   (0,0),(-1,-1), 12),
                ("RIGHTPADDING",  (0,0),(-1,-1), 12),
                ("TOPPADDING",    (0,0),(-1,-1), 9),
                ("BOTTOMPADDING", (0,0),(-1,-1), 9),
            ]))
            wrapper = Table([["", role_label], ["", msg_tbl]], colWidths=[54, 450])

        story.append(KeepTogether([wrapper]))

        # Embedded chart
        if plot_url:
            try:
                fname = urllib.parse.unquote(plot_url.split("/")[-1])
                user_home   = Path.home() / ".crewlyze"
                outputs_base = Path(os.getenv("CREWLYZE_OUTPUTS_DIR", str(user_home / "outputs")))
                png_file = outputs_base / session_id / fname

                if png_file.exists():
                    img_tbl, fig_cap = _img_flowable(png_file, max_w=380, max_h=260)
                    if img_tbl:
                        story.append(Spacer(1, 4))
                        story.append(KeepTogether([img_tbl, fig_cap]))
            except Exception as exc:
                print(f"Chat PDF image embed failed: {exc}")

        story.append(Spacer(1, 10))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
